### ISSUE TITLE
برنامه کار نمی‌کنه

### ISSUE THREAD

**Issue by xmha97** [ArefDev/BeepDl#1]
سلام
برنامه کار نمی‌کنه
![image](https://user-images.githubusercontent.com/23485114/106288297-180e4100-625d-11eb-8c70-a5e6990f4eee.png)

**Comment by ArefDev** [comment]
Hi Dear Muhammad Hussein
I tested the program in Windows 7 (VM) and it's working perfectly.
Would you please check the output of the console?


![win7](https://user-images.githubusercontent.com/74472396/106312944-af36c100-627c-11eb-9978-96e5a6089efc.png)

**Comment by xmha97** [comment]
This app working fine.
The problem was that I was using Python (Microsoft Store Edition):
https://www.microsoft.com/store/productId/9P7QFQMJRFP7
![image](https://user-images.githubusercontent.com/23485114/107025531-d16d9900-67be-11eb-8469-438923b0cd91.png)
Thanks <3
